package model.readonlyview;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 11 12:29:40 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DataRVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DataRVOImpl() {
    }
}

